package-lock.json
package.json
server/db/models/order.js
server/db/models/sock.js
server/db/models/user.js

Initial model commit

---

client/components/home.js
client/components/home.spec.js
client/components/index.js
client/routes.js
package-lock.json
package.json
public/index.html

Changed *UserHome to *Home and updated metainfo

---

server/db/models/index.js

Initial associations made

---

client/routes.js
server/db/models/index.js
server/db/models/sock.js
server/db/models/user.js

fixed the bugs

---

seed.js

More Work On Seed File

---

client/store/index.js
client/store/socks.js

I was looking for some work to do on the project, and it seemed like this was a possible next step that we would need to be able to work on the sock view component. I created a sock reducer and combined it with the current reducer for the user.

created socks reducer to add socks to store state with socks api route

---

package.json
seed.js

Added final catagories

---

package.json

fixed 'npm seed' script

---

client/components/adultSocks.js
client/routes.js

Route hooked up to localhost:8080/adults should currently display all sock pictures

can display all socks currently on adult page

---

client/components/adultSocks.js
seed.js

filters by adult size now

---

client/components/kidSocks.js
client/routes.js

set up route to kids socks

---

client/routes.js

fixed route  path to /kids by adding exact path

---

seed.js

changed single photo

---

client/components/adultSocks.js
client/components/kidSocks.js
client/store/socks.js
server/api/adults.js
server/api/index.js
server/api/kids.js

Kids reducer

---

client/components/navbar.js
client/components/pageNotFound.js
client/routes.js
client/store/user.js
public/index.html
server/auth/index.js

- added basic "not found" page if URL route does not match any of ours. 
- Confirmed login stores user on state.
- Re-wired route upon login to bring you back home (previously stayed on login page)

working on login stuff

---

client/components/kidSocks.js
client/components/navbar.js
client/routes.js
server/api/adults.js
server/api/index.js
server/api/kids.js
server/api/socks.js

Revert "fixing non-dry kids routes"

---

client/components/adultSocks.js
client/components/kidSocks.js
client/routes.js
client/store/socks.js
public/style.css
seed.js
server/api/socks.js
server/db/models/index.js
server/db/models/sock.js

This PR is not really meant to be merged. Instead I'd recommend you look at the notes below (for general comments) and files changed tab (for the inline comments), the maybe make issues in GitHub for any changes you want to make based off these notes, and then close this PR.
- Excellent committing frequently, expressive messages
- Recommend standardizing your commit message format, a lot of opinions, more important than choosing the right is just choosing one (discussing it), but [here's one that I like](https://seesparkbox.com/foundry/semantic_commit_messages)
- Consider using issues instead of just cards (cards auto populate based off of issues or something)
- Feel empowered to change the issue / PR / etc github templates in you `.github` folder
- Take a little time to make the README …

Code review meeting feedback

---

client/components/index.js
client/components/kidSocks.js
client/components/navbar.js
client/components/signup-form.js
client/routes.js
client/store/user.js
public/style.css
server/db/models/user.js

1. Changed signup form:
- Now no longer shared with login form
- Has more fields than login
- Tested and adds user to DB, changes state to reflect logged in user
- Required some changes to store (thunk for signup)
- We may have to change the name of ‘auth-form’ and all auth-form components to reflect something along the lines of ‘login form’
2. Navbar now renders userPhoto when a user is logged in
- Currently working on getting it to drop down with account details & logout
3. Required User's photoURL to be Sequelize.TEXT in case of long URL (vs Sequelize.STRING)
4. Invalid DOM property, need to change a 'class' to 'className' in kidsSocks.js (didn’t wanna cause any merge conflicts)

login photo works and can sign up with all info

---

.github/PULL_REQUEST_TEMPLATE.md
client/components/adultSocks.js
client/components/kidSocks.js
client/components/pageNotFound.js
client/routes.js
server/api/index.js

update pull request format to fit the information we seem to include naturally

Default pull request

---

client/components/adultSocks.js
client/components/kidSocks.js

Capitalized AdultSocks and KidSocks components
=(^.^)=

style: capitalize components

---

server/db/models/sock.js
server/db/models/sock.spec.js
server/db/models/user.spec.js

- added tests for user model
- added test for sock model
- is now possible to run tests for models.
-no
=(^.^)=
/|    |\
_ /  /\  \__________

Model tests

---

public/style.css

adjust dropdown size to account for letter spacing
"account details" on one line
=(^.^)=

style: adjust dropdown size to account for letter spacing

---

client/components/pageNotFound.js
client/components/user-dropdown.js
public/style.css

- style.css, pageNotFound.js, user-dropdown.js
- added a little 'me' text below user's pic with a small arrow next to it
- made our 404 page complete with message and link back to home
- not that I know of
=(^.^)=

style: me button with arrow below userpic - 404 component updates

---

client/components/order-button.js
client/components/page-not-found.js
client/store/user.js
server/api/index.js
server/api/orders.js
server/api/users.js
server/db/models/index.js
server/db/models/order.js

added ability for user to create a cart
see above
more work
=(0.0)=

user can create a new order

---

client/components/adult-socks.js
client/components/category-socks.js
client/components/single-sock.js
client/routes.js
client/store/socks.js
public/style.css
server/api/socks.js

routes for category filtered socks, component too, thunk to get sock by category, it works!
can filter by category
we will change route to go to category/categoryName because of socks/sockId conflict in routes.
figure out spot to add filter links.
=(^.^)=

Category routes

---

client/components/adult-socks.js
client/components/category-menu.js
client/components/category-socks.js
client/components/kid-socks.js
client/components/navbar.js
client/components/single-sock.js
public/style.css

category-socks.js
category-menu.js
kid-socks.js
adult-socks.js
style.css
Can now view by category
no
=(^.^)=

Category menu

---

seed.js

sorry for the multiple pull requests, had an issue when making multiple commits to the same branch

fix: kid's socks no longer have adult sizes

---

server/api/orders.js

server/api/orders.js
no longer spits 500 error when using the post route with user id
X
X
=(^.^)=

fix: Fixed 500 error when trying to create a new row in Order Table

---

server/api/socks.spec.js
server/db/models/cart-item.js
server/db/models/index.js

refactored the sock routes test
can test for serving up single sock by id
=(^.^)=

test: refactored sock routes and added find-by-id test

---

client/components/adult-socks.js
client/components/size-dropdown.js
client/components/sock-list.js

clean up dead code
fix key props in components using index
=(^.^)=

Post review refactor

---

client/components/cart.js
client/store/socks.js
server/api/orders.js
server/db/models/cart-item.js
server/db/models/index.js

remove now works
you can choose to not buy something you previously wanted to
probbably
=(^.^)=

removing works

---

client/components/Checkout.js
client/components/cart.js
client/components/stripe.js
client/routes.js
constants/server.js
constants/stripe.js
package-lock.json
package.json
server/api/index.js
server/api/payments.js
server/api/socks.spec.js
server/constants/stripe.js

stripe component created and connected
can make payment with stripe
need to hook up stripe to cart. ***EVERYONE NPM INSTALL***
=(^.^)=

feat: stripe payment button up and running

---

client/components/Checkout.js
client/components/cart.js

chore: connect stripe button to current store/cart total

---

client/components/Checkout.js
client/components/cart.js
client/components/user-dropdown.js
public/style.css

User can checkout
Price in checkout not reflects the users cart
Empty cart on purchase and mark the order as sold.
=(^.^)=

Checkout done kindof

---

client/components/cart.js

fix: checkout is imported into cart
=(^.^)=

fix: checkout is imported into cart

---

client/components/order-button.js
client/components/quantity-dropdown.js
client/components/single-sock.js
client/components/size-dropdown.js
public/style.css

- single-sock.js, both dropdowns, style.css, order-button.hs
- single sock page is now styled to completion
- still need to reset form upon adding to cart
- negative
=(^.^)=

More style

---

client/components/cart-icon.js
client/components/cart.js
client/components/category-menu.js
client/components/category-socks.js
client/components/navbar.js
client/components/order-history.js
client/components/related-socks.js
client/components/sock-list.js
client/components/user-dropdown.js
client/components/utils.js
client/routes.js
client/store/orders.js
client/store/socks.js
server/api/orders.js
server/api/socks.spec.js
server/db/models/order.js

Refactored store to account for edge cases and redundancies
Moved formatDate function to utils file
=(^.^)=

Store refactor

---

client/components/utils.js

utils file
app runs again
no
=(^.^)=

fix: export on format date was causing an error

---

client/components/navbar.js
client/components/single-sock.js

- single-sock view
- form resets upon adding to cart
- would like to make cart glow when cart has an item, but did not want to mess with style as James & Laura are in it.
=(^.^)=

feat: form resets when added to cart

---

client/components/cart.js
client/components/category-menu.js
client/components/navbar.js
client/components/single-sock.js

- cart.js
- had an opactity error where the user dropdown was not fully white due to the below border's opacity
- nope
- nope
=(^.^)=

Dropdown fix

---

client/components/Checkout.js
client/components/cart.js
client/components/category-menu.js
client/components/start-shopping.js
client/store/socks.js
public/style.css
server/api/orders.js

a fair amount of files
users cart is marked as sold and visually "emptyed" when they purchase socks
nope
=(^.^)=

fix: cart now emptys on purchase

---

client/components/home.js
public/style.css

fix: background images don't repeat

---

client/components/start-shopping.js
public/style.css
seed.js

- just messed with a small div
- start shopping button on empty cart was spreading the link on the entire page
- nonono
-nonono
=(^.^)=

chore: styled cart a little more - fixed megabutton

---

client/components/category-socks.js
public/style.css

category header is readable. 
=(^.^)=

style: white background to category header title

---

client/components/adult-socks.js
client/components/kid-socks.js

fix: adult/kid category style

---

client/components/cart.js
client/components/single-sock.js
client/store/user.js

guest cart now receives user info 
a bug
no
=(^.^)=

fix: guest cart now receives user info instead of empty object

---

client/components/adult-socks.js
client/components/adult-socks.spec.js

wrote react test for adult socks that passes
=(^.^)=

test: set up react test for adult sock component

---

client/components/cart.js

fix: cart header styled

---

client/components/home.js
client/components/index.js

Deploy test
